### ISSUE TITLE
Rework package functions to use sf instead of sp package

### ISSUE THREAD

**Issue by leppott** [Blocktt/KDHEtools#2]
When creating package documentation get warning of retirement of sp supporting packages.  Need to move to sf package.  Supporting ending October 2023.

![image](https://github.com/Blocktt/KDHEtools/assets/24276278/6d5cdeea-1126-415a-9601-39e868ef5c24)

**Comment by leppott** [comment]
Added issue in WDEQtools repo.

https://github.com/Blocktt/WDEQtools/issues/1

**Comment by Blocktt** [comment]
No mapping package used in this app. Will resolve sp to sf conversion in other apps as time allows.
