### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by leppott** [Blocktt/KDHEtools#5]
Opening links uses the current window and moves away from the Shiny app.

Links to files and such would be better if open in a new tab or window so don't lose progress in the Shiny app.

**Comment by leppott** [comment]
Hyperlinks add “target = “_blank””.

**Comment by Blocktt** [comment]
Issue resolved in [v0.1.2.9062](https://github.com/Blocktt/KDHEtools/commit/cfdce01d81391e6fea4c3051db7edc87f2c1d7d0)
